### ISSUE TITLE
Migration Error - Production

### ISSUE THREAD

**Issue by jmilljr24** [rubyforgood/homeward-tails#1187]
Check [kamal deploy workflow](https://github.com/rubyforgood/homeward-tails/actions/runs/12039017394/job/33565955334#step:7:1913) for more details
```
 ERROR 2024-11-26T21:09:10.828100602Z bin/rails aborted!
2024-11-26T21:09:10.828267504Z StandardError: An error has occurred, this and all later migrations canceled: (StandardError)
2024-11-26T21:09:10.828273404Z 
2024-11-26T21:09:10.828275804Z PG::NotNullViolation: ERROR:  column "locatable_type" of relation "locations" contains null values
2024-11-26T21:09:10.828278304Z /rails/db/migrate/20241122053814_add_locatable_to_locations.rb:6:in `block in change'
2024-11-26T21:09:10.828280604Z /rails/db/migrate/20241122053814_add_locatable_to_locations.rb:3:in `change'
2024-11-26T21:09:10.828282704Z 
2024-11-26T21:09:10.828284604Z Caused by:
2024-11-26T21:09:10.828286704Z ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  column "locatable_type" of relation "locations" contains null values (ActiveRecord::NotNullViolation)
2024-11-26T21:09:10.828291904Z /rails/db/migrate/20241122053814_add_locatable_to_locations.rb:6:in `block in change'
2024-11-26T21:09:10.828294104Z /rails/db/migrate/20241122053814_add_locatable_to_locations.rb:3:in `change'
2024-11-26T21:09:10.828296204Z 
2024-11-26T21:09:10.828298204Z Caused by:
2024-11-26T21:09:10.828300204Z PG::NotNullViolation: ERROR:  column "locatable_type" of relation "locations" contains null values (PG::NotNullViolation)
2024-11-26T21:09:10.828302504Z /rails/db/migrate/20241122053814_add_locatable_to_locations.rb:6:in `block in change'
2024-11-26T21:09:10.828304604Z /rails/db/migrate/20241122053814_add_locatable_to_locations.rb:3:in `change'
```

**Comment by jmilljr24** [comment]
@mononoken Looks like it was this [migration](https://github.com/rubyforgood/homeward-tails/pull/1169/files#diff-903cca8b1721a9024eb9b70b04109157bdd7253584f5f64ebfa2800d6083b03a)
